version: "3.7"

services:
  redis:
    image: redis
    restart: always

  web:
    build: .
    command: python /usr/src/improve_your_file/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/improve_your_file
    ports:
      - 8000:8000
